### ISSUE TITLE
Not finding ID attribute

### ISSUE THREAD

**Issue by pcrum** [voipir/rust-xmlsec#1]
Thank you for putting this project together. I'm trying to verify signature of a saml response and receiving the following error below. I believe it's not finding the appropriate ID attribute. Other libraries allow you to set the ID attribute. How would I go about doing that in this project?

func=xmlSecXPathDataExecute:file=xpath.c:line=247:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('_30b74cd0e1cadd39f7a6a71d88baec3a7d6f2ab175')); xml error: 0: NULL
func=xmlSecXPathDataListExecute:file=xpath.c:line=330:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformXPathExecute:file=xpath.c:line=431:obj=xpointer:subj=xmlSecXPathDataListExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2109:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1045:obj=xpointer:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxExecute:file=transforms.c:line=1092:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1408:obj=unknown:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessReferences:file=xmldsig.c:line=753:obj=Reference:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=517:obj=unknown:subj=xmlSecDSigCtxProcessReferences:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=346:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed:

**Comment by lweberk** [comment]
Hi there,

cannot really say for sure of the top of my head. Looks like no initialization of the underlying xmlsec happened before signature verification.

Can you provide me with the usage code to paint a more complete picture that might help me what is going wrong?

**Comment by pcrum** [comment]
Essentially I'm trying to verify xml signature from a saml response generated via samling. https://capriza.github.io/samling/samling.html. 

`use xmlsec::XmlSecTemplateBuilder;
use xmlsec::XmlSecDocumentTemplating;
use xmlsec::XmlSecCanonicalizationMethod;
use xmlsec::XmlSecSignatureMethod;

use xmlsec::XmlSecKey;
use xmlsec::XmlSecKeyFormat;
use xmlsec::XmlSecSignatureContext;

use libxml::parser::Parser           as XmlParser;
use libxml::tree::document::Document as XmlDocument;

fn main() {
    
    let parser = XmlParser::default();

    let document: XmlDocument = parser.parse_file("sign2-doc.xml")
        .expect("Failed to load document create template for and sign/verify");
    
    let key = XmlSecKey::from_file("key.pem", XmlSecKeyFormat::Pem, None)
        .expect("Failed to properly load key from file");
    
    let mut sigctx = XmlSecSignatureContext::new();
    sigctx.insert_key(key);

    let valid = sigctx.verify_document(&document)
        .expect("Failed to verify document");

    if !valid {
        panic!("Document signature is not valid");
    }
}
`

**Comment by lweberk** [comment]
Ok yeah, sorry it seems I did not properly read the original message you wrote. Yes, it is not finding the ID and yes there are ways to specify the ID by adding "id attributes". Its kind of obscure and undocumented, and I found it by perusing the xmlsec cli tool sources... currently not in the wrapper but I'll add it later today. In the meantime;

```rust
//!
//! Common utilities needed by this module
//!
use libxml::bindings;

use crate::XmlDocument;
use crate::XmlDocumentExt;

use std::os::raw::c_uchar;
use std::ffi::CString;
use std::ptr::null_mut;


pub fn insert_id_attr(doc: &XmlDocument, node: &str, attr: &str, namespaces: Option<&[(&str, &str)]>)
{
    let subjnodes;

    if let Some(nss) = namespaces {
        subjnodes = doc.find_nodes_ns(node, nss);
    } else {
        subjnodes = doc.find_nodes(node);
    }

    for node in &subjnodes
    {
        if let Some(attrnode) = node.get_property_node(attr)
        {
            let docptr  = doc.doc_ptr();
            let attrptr = attrnode.node_ptr() as *mut bindings::_xmlAttr;

            let id     = attrnode.get_content();
            let cid    = CString::new(id.clone()).unwrap();
            let cidptr = cid.as_ptr() as *mut c_uchar;

            let existing = unsafe { bindings::xmlGetID(docptr, cidptr) };

            if existing == null_mut() {
                unsafe { bindings::xmlAddID(null_mut(), docptr, cidptr, attrptr) };
            } else if existing != attrptr {
                panic!("Error: duplicate ID attribute: {}", id);
            }
        }
    }
}
```

Hodgepodge, but hope it helps you out. Please bear with me.

You'll have to fill in the extension parts over XmlDocument yourself. This is from a downstream project that is a little constrained by the current rust-libxml API.

**Comment by lweberk** [comment]
Ok, added via an extension trait; XmlSecDocumentExt, being more precise its ::specify_idattr. Also enhanced the example with its usage and you can also have a look at the test that covers the functionality.

If you encounter any problems, please re-open this issue.
