### ISSUE TITLE
Expose wrapped internals for ease of adhoc extension

### ISSUE THREAD

**Issue by lweberk** [voipir/rust-xmlsec#5]
Make it easier to extend functionality of this wrapper by having API make the wrapped internals available under "unsafe" conditions. This can be beneficial for quick and dirty extension for not yet wrapped functionality without having to fork or otherwise handle upstream. 

The downside for something like this, which in my perspective is not a stopper in itself, is that it disincentives the contributing back such an extension to upstream. 

Design-wise the idea is to settle for the overarching use of `unsafe fn as_ptr() -> *rawPtr` and also the availability of the bindgen generated low level bindings which currently are private to the `bindings` module. The combination of both should enable most of what might be needed.

- `as_ptr(&self) -> *wrappedXmlStructure` to borrow the wrapped structure pointer
- `into_ptr(self) -> *wrappedXmlStructure` to move out the wrapped structure pointer, all the while suppressing the cleanup in the drop call.

Stakeholders;
- @JoshuaNitschke

**Comment by lweberk** [comment]
Ok first question to answer is how to consume and pass out the underlying pointer without drop being called and cleaning up the underlying C library structure. 

One possible way that comes to mind is a sentinel in the wrapper that signals whether the drop call is to actually drop or be a noop. 

Is there a more elegant way though?

**Comment by JoshuaNitschke** [comment]
@lweberk I'm happy to extend the builder for what I need as opposed to just exposing the raw functionality.  

The only feature that is lacking for me (right now) is that I can't add the X509IssuerSerial block into the x509data.
```
 <dsig:X509IssuerSerial>
     <dsig:X509IssuerName>redacted</dsig:X509IssuerName>
     <dsig:X509SerialNumber>redacted</dsig:X509SerialNumber>
 </dsig:X509IssuerSerial>
```

Maybe we just add another option? `x509issuer_serial(bool)` (that defaults to false)?

```
doc.template()
        .canonicalization(XmlSecCanonicalizationMethod::ExclusiveC14N)
        .signature(XmlSecSignatureMethod::RsaSha1)
        .keyname(true)
        .keyvalue(true)
        .x509data(true)
        .x509issuer_serial(true)
        .uri("ReferencedID")
        .done();
```

All that issuer data is in the cert (obviously), which has already been given to the context.  I'm not sure if xmlsec can get at it on its own as I am not very familiar with the library, I use https://docs.rs/openssl/latest/openssl/ for my use case.

**Comment by lweberk** [comment]
That is actually a better overall solution for your case. And yes the library [does support this](https://www.aleksey.com/xmlsec/api/xmlsec-templates.html#xmlSecTmplX509DataAddIssuerSerial). Other than requiring a handle on the x509 data node itself instead of the dsig node we are handling, it is straight forward to add. If you want to take a shot at it, I'd gladly merge your PR.

Design-wise we have 2 options of which in either there should be an additional field in the template builder struct optionally holding the pointer to the x509data node. Such that if someone sets `x509issuer_serial(true)` and `x509data(true)` was not previously set it;
- Returns a `Err` on the `x509issuer_serial(true)`
- Implies `x509data(true)` to be set. This causes less friction and given both are runtime scenarios I'd prefer this one.

Otherwise I'd consider this discussion as off topic in this issue, since it still stands true due to the rationale that we are all consenting adults and as such should have access to the underlying objects in the wrapper in an `unsafe`ly marked manner.
